/** LinkedIn profiles supplied in “TTG Member Information - Sheet6.csv”. */
export const memberLinkedins: Record<string, string> = {
  "Shaurya Prakaash": "https://www.linkedin.com/in/shaurya-prakaash/",
  "Maya Nayberg": "https://www.linkedin.com/in/maya-nayberg-82363629a/",
  "Anthony Volkov": "https://www.linkedin.com/in/anthony-volkov-ucsd/",
  "Michael Valdivia": "https://www.linkedin.com/in/valina-micheal-4462b4241/",
  "Noor Dhillon": "https://www.linkedin.com/in/noor-s-dhillon/",
  "Titus Cheng": "https://www.linkedin.com/in/titus-cheng-63396129a/",
  "Jacqueline Dao": "https://www.linkedin.com/in/jacqueline-dao-8b89b8328/",
  "Micah Watson": "https://www.linkedin.com/in/micah-watson-/",
  "Prisca Lee": "https://www.linkedin.com/in/prisca-lee-b0917934a/",
  "Shiyo Ohashi": "https://www.linkedin.com/in/shiyo-ohashi/",
  "Anirudh Iyengar": "https://www.linkedin.com/in/anirudh-iyengar-0a5627282/",
  "Sohan Shingade": "https://www.linkedin.com/in/sohan-shingade/",
  "Divyansh Kanodia": "https://www.linkedin.com/in/divyansh-kanodia-0978611a9/",
  "Gilad Segal": "https://www.linkedin.com/in/gilad-segal-777g888/",
  "Matthieu Fuller": "https://www.linkedin.com/in/matthieu-fuller/",
  "Saksham Arora": "https://www.linkedin.com/in/saksham-arora-a20ab82b1/",
  "Alibek Tolegen": "https://www.linkedin.com/in/alibektolegen/",
  "Alper Kaan Oguzhan": "https://www.linkedin.com/in/alper-kaan-oguzhan-25071038a/",
  "Ryan Hayden": "https://www.linkedin.com/in/-ryanhayden-/",
  "Sulthan Uways Dinova": "https://www.linkedin.com/in/sulthan-uways/",
  "Aarzu Singh": "https://www.linkedin.com/in/aarzu-singh-ucsd/",
  "Clevon Ho": "https://www.linkedin.com/in/clevon-ho/",
  "Roma Patel": "https://www.linkedin.com/in/roma-patel-263a002b4/",
  "Ruhan Karthik": "https://www.linkedin.com/in/ruhan-karthik-5b2b77314/",
  "Daniel Solichin": "https://www.linkedin.com/in/daniel-solichin/",
  "Thienan Bui": "https://www.linkedin.com/in/thienandangbui/",
  "Annie Zhang": "https://www.linkedin.com/in/annie-zhang-6aa986272/",
  "Elias Willmert": "https://www.linkedin.com/in/elias-willmert/",
  "Myra Chou": "https://www.linkedin.com/in/myra-chou-714738261/",
  "Trey Torres": "https://www.linkedin.com/in/trey-torres-a0a3aa274/",
  "Abby Walker": "https://www.linkedin.com/in/abigail-walker-00792b394/",
  "Abhishai Ganta": "https://www.linkedin.com/in/abhishai-ganta-0223962b8/",
  "Aditya Mandloi": "https://www.linkedin.com/in/aditya-mandloi-3b34b830a/",
  "Ashwin Kannan": "https://www.linkedin.com/in/ashwin-kannan-3a90a2312/",
  "Shea Elmore": "https://www.linkedin.com/in/shea-elmore/",
  "Allison Xu": "https://www.linkedin.com/in/allison-xu-924653376/",
  "Clarisa Mutia": "https://www.linkedin.com/in/clarisa-rahmawati-mutia-59351a27b/",
  "Daniel Castro": "https://www.linkedin.com/in/daniel-castro-aspiring-cpa/",
  "Kaavya Verma": "https://www.linkedin.com/in/kaavya-verma-b88b572a2/",
  "Miraj Bhalala": "https://www.linkedin.com/in/miraj-bhalala-2b8242283/",
  "Ramon De La O": "https://www.linkedin.com/in/ramon-de-la-o-2029a3389/",
  "Sattvik Kurani": "https://www.linkedin.com/in/sattvikkurani30/",
  "Sean Lee": "https://www.linkedin.com/in/seanlee433/",
  "Naliya Montebon": "https://www.linkedin.com/in/naliya-montebon-036906393/",
  "Hudson Betts": "https://www.linkedin.com/in/hudson-betts/",
  "Srihan Basvapatri": "https://www.linkedin.com/in/srihanb/",
};
