"use client";

import { FormEvent, useEffect, useState } from "react";

const api = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:3000";
type RecordValue = Record<string, unknown>;
async function request(path: string, init?: RequestInit) {
  const response = await fetch(`${api}/api/v1${path}`, { credentials: "include", headers: { "content-type": "application/json", ...(init?.headers ?? {}) }, ...init });
  const payload = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(payload.error ?? "Request failed");
  return payload.data;
}
const number = (value: unknown) => typeof value === "number" ? value : Number(value ?? 0);
const money = (value: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(number(value));

export function BrokerageWorkspace() {
  const [portfolio, setPortfolio] = useState<RecordValue | null>(null); const [status, setStatus] = useState<RecordValue | null>(null); const [proposals, setProposals] = useState<RecordValue[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const refresh = async () => { setError(""); try { const [nextStatus, nextPortfolio, nextProposals] = await Promise.all([request("/assetmgmt/brokerage/status"), request("/assetmgmt/brokerage/portfolio"), request("/assetmgmt/brokerage/proposals")]); setStatus(nextStatus); setPortfolio(nextPortfolio); setProposals(nextProposals); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load brokerage data"); } };
  useEffect(() => { void refresh(); }, []);
  const act = async (path: string, body?: unknown) => { setBusy(true); setError(""); try { await request(path, { method: "POST", body: body === undefined ? undefined : JSON.stringify(body) }); await refresh(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Action failed"); } finally { setBusy(false); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const type = String(form.get("type")); const order: RecordValue = { symbol: String(form.get("symbol")).trim().toUpperCase(), side: form.get("side"), type, time_in_force: form.get("time_in_force") };
    for (const key of ["qty", "notional", "limit_price", "stop_price", "trail_price", "trail_percent"]) { const value = String(form.get(key) ?? "").trim(); if (value) order[key] = Number(value); }
    const advanced = String(form.get("advanced") ?? "").trim(); if (advanced) try { Object.assign(order, JSON.parse(advanced)); } catch { setError("Advanced order details must be valid JSON"); return; }
    await act("/assetmgmt/brokerage/proposals", { order, thesis_id: String(form.get("thesis_id") ?? "").trim() || undefined }); event.currentTarget.reset(); };
  const snapshot = portfolio?.snapshot as RecordValue | null | undefined; const account = snapshot?.account as RecordValue | undefined; const positions = Array.isArray(snapshot?.positions) ? snapshot!.positions as RecordValue[] : [];
  return <section className="mt-8">
    <div className="flex flex-wrap items-center justify-between gap-4 border border-[#c79a3b]/40 bg-[#c79a3b]/10 p-5"><div><p className="text-[10px] font-bold tracking-[.18em] text-[#c79a3b]">ALPACA · SHARED TTG ACCOUNT</p><p className="mt-2 text-sm text-white/70">{status?.configured ? snapshot ? `Last synchronized ${new Date(String(snapshot.synced_at)).toLocaleString()}` : "Ready to synchronize the live account." : "Alpaca credentials have not been configured."}</p></div><button disabled={!status?.configured || busy} onClick={() => void act("/assetmgmt/brokerage/sync")} className="border border-[#c79a3b] px-4 py-3 text-xs font-bold tracking-[.14em] text-[#f0cb7b] disabled:opacity-40">SYNC LIVE ACCOUNT</button></div>
    {error && <p className="mt-4 border border-[#ff9f7d]/50 bg-[#ff9f7d]/10 p-4 text-sm text-[#ffb19a]">{error}</p>}
    {account && <div className="mt-5 grid gap-3 md:grid-cols-4"><Metric label="Portfolio value" value={money(account.portfolio_value)} /><Metric label="Cash" value={money(account.cash)} /><Metric label="Buying power" value={money(account.buying_power)} /><Metric label="Account status" value={String(account.status ?? "unknown").toUpperCase()} /></div>}
    <div className="mt-5 grid gap-5 xl:grid-cols-[minmax(0,1fr)_390px]"><div className="border border-white/15 bg-white/5"><div className="border-b border-white/15 p-5"><p className="text-[10px] font-bold tracking-[.16em] text-white/45">LIVE POSITIONS</p></div>{positions.length ? <div className="overflow-x-auto"><table className="w-full min-w-[600px] text-sm"><thead className="border-b border-white/10 text-left text-[10px] tracking-[.14em] text-white/45"><tr><th className="p-4">SYMBOL</th><th className="p-4">QTY</th><th className="p-4">MARKET VALUE</th><th className="p-4">UNREALIZED P/L</th></tr></thead><tbody>{positions.map((position) => <tr key={String(position.asset_id ?? position.symbol)} className="border-b border-white/10 last:border-0"><td className="p-4 font-medium">{String(position.symbol)}</td><td className="p-4 text-white/70">{String(position.qty)}</td><td className="p-4">{money(position.market_value)}</td><td className={`p-4 ${number(position.unrealized_pl) >= 0 ? "text-emerald-300" : "text-[#ff9f7d]"}`}>{money(position.unrealized_pl)}</td></tr>)}</tbody></table></div> : <p className="p-5 text-sm text-white/55">Synchronize the account to load live positions.</p>}</div>
      <form onSubmit={submit} className="border border-white/15 bg-[#101010] p-5"><p className="text-[10px] font-bold tracking-[.16em] text-[#c79a3b]">SUBMIT TRADE PROPOSAL</p><p className="mt-2 text-xs leading-5 text-white/55">An officer must approve this exact order before it is sent to Alpaca.</p><div className="mt-4 grid gap-3"><Field name="symbol" label="Symbol" required /><div className="grid grid-cols-2 gap-3"><Select name="side" label="Side" values={["buy", "sell"]} /><Select name="type" label="Order type" values={["market", "limit", "stop", "stop_limit", "trailing_stop"]} /></div><div className="grid grid-cols-2 gap-3"><Field name="qty" label="Quantity" type="number" /><Field name="notional" label="Notional USD" type="number" /></div><Select name="time_in_force" label="Time in force" values={["day", "gtc", "opg", "cls", "ioc", "fok"]} /><div className="grid grid-cols-2 gap-3"><Field name="limit_price" label="Limit price" type="number" /><Field name="stop_price" label="Stop price" type="number" /></div><div className="grid grid-cols-2 gap-3"><Field name="trail_price" label="Trail price" type="number" /><Field name="trail_percent" label="Trail %" type="number" /></div><Field name="thesis_id" label="Thesis ID (optional)" /><label className="text-[10px] font-bold tracking-[.12em] text-white/55">ADVANCED ALPACA DETAILS (OPTIONAL)<textarea name="advanced" placeholder='{"order_class":"bracket","take_profit":{"limit_price":...}}' className="mt-2 min-h-20 w-full border border-white/20 bg-black/20 p-3 font-mono text-xs font-normal tracking-normal text-white" /></label><button disabled={busy || !status?.configured} className="bg-[#c79a3b] px-4 py-3 text-xs font-bold tracking-[.14em] text-[#101010] disabled:opacity-40">SUBMIT FOR APPROVAL</button></div></form></div>
    <div className="mt-5 border border-white/15 bg-white/5"><div className="border-b border-white/15 p-5"><p className="text-[10px] font-bold tracking-[.16em] text-white/45">ORDER APPROVAL QUEUE</p></div>{proposals.length ? <div className="divide-y divide-white/10">{proposals.map((proposal) => { const order = proposal.payload as RecordValue; const pending = proposal.status === "proposed"; return <article key={String(proposal.id)} className="flex flex-wrap items-center justify-between gap-4 p-5"><div><p className="font-medium">{String(order.side).toUpperCase()} {String(order.symbol ?? "MULTI-LEG")} · {String(order.type).toUpperCase()}</p><p className="mt-1 text-xs text-white/55">{String(order.qty ?? order.notional)} · proposed by {String(proposal.proposed_by_name)} · {String(proposal.status).replaceAll("_", " ")}</p></div><div className="flex gap-2">{pending && <button disabled={busy} onClick={() => void act(`/assetmgmt/brokerage/proposals/${proposal.id}/approve`, { note: "Approved in TTG" })} className="border border-[#c79a3b] px-3 py-2 text-[10px] font-bold tracking-[.12em] text-[#f0cb7b]">APPROVE & SEND</button>}{["proposed", "submitted"].includes(String(proposal.status)) && <button disabled={busy} onClick={() => void act(`/assetmgmt/brokerage/proposals/${proposal.id}/cancel`)} className="border border-white/25 px-3 py-2 text-[10px] font-bold tracking-[.12em]">CANCEL</button>}</div></article>; })}</div> : <p className="p-5 text-sm text-white/55">No trade proposals yet.</p>}</div>
  </section>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="border border-white/15 bg-white/5 p-4"><p className="text-[10px] font-bold tracking-[.14em] text-white/45">{label.toUpperCase()}</p><p className="mt-2 text-xl">{value}</p></div>; }
function Field({ name, label, type = "text", required = false }: { name: string; label: string; type?: string; required?: boolean }) { return <label className="text-[10px] font-bold tracking-[.12em] text-white/55">{label.toUpperCase()}<input name={name} type={type} required={required} min={type === "number" ? "0" : undefined} step={type === "number" ? "any" : undefined} className="mt-2 w-full border border-white/20 bg-black/20 px-3 py-2 text-sm font-normal tracking-normal text-white" /></label>; }
function Select({ name, label, values }: { name: string; label: string; values: string[] }) { return <label className="text-[10px] font-bold tracking-[.12em] text-white/55">{label.toUpperCase()}<select name={name} className="mt-2 w-full border border-white/20 bg-black/20 px-3 py-2 text-sm font-normal tracking-normal text-white">{values.map((value) => <option key={value} value={value}>{value.toUpperCase()}</option>)}</select></label>; }
